// Code generated by MockGen. DO NOT EDIT.
// Source: services.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	context "context"
	reflect "reflect"

	models "github.com/dimsonson/go-yandex-diploma-tpl/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockStorageProvider is a mock of StorageProvider interface.
type MockStorageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStorageProviderMockRecorder
}

// MockStorageProviderMockRecorder is the mock recorder for MockStorageProvider.
type MockStorageProviderMockRecorder struct {
	mock *MockStorageProvider
}

// NewMockStorageProvider creates a new mock instance.
func NewMockStorageProvider(ctrl *gomock.Controller) *MockStorageProvider {
	mock := &MockStorageProvider{ctrl: ctrl}
	mock.recorder = &MockStorageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageProvider) EXPECT() *MockStorageProviderMockRecorder {
	return m.recorder
}

// StorageAuthorizationCheck mocks base method.
func (m *MockStorageProvider) StorageAuthorizationCheck(ctx context.Context, login, passwHex string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageAuthorizationCheck", ctx, login, passwHex)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorageAuthorizationCheck indicates an expected call of StorageAuthorizationCheck.
func (mr *MockStorageProviderMockRecorder) StorageAuthorizationCheck(ctx, login, passwHex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageAuthorizationCheck", reflect.TypeOf((*MockStorageProvider)(nil).StorageAuthorizationCheck), ctx, login, passwHex)
}

// StorageConnectionClose mocks base method.
func (m *MockStorageProvider) StorageConnectionClose() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StorageConnectionClose")
}

// StorageConnectionClose indicates an expected call of StorageConnectionClose.
func (mr *MockStorageProviderMockRecorder) StorageConnectionClose() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageConnectionClose", reflect.TypeOf((*MockStorageProvider)(nil).StorageConnectionClose))
}

// StorageCreateNewUser mocks base method.
func (m *MockStorageProvider) StorageCreateNewUser(ctx context.Context, login, passwH string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageCreateNewUser", ctx, login, passwH)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorageCreateNewUser indicates an expected call of StorageCreateNewUser.
func (mr *MockStorageProviderMockRecorder) StorageCreateNewUser(ctx, login, passwH interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageCreateNewUser", reflect.TypeOf((*MockStorageProvider)(nil).StorageCreateNewUser), ctx, login, passwH)
}

// StorageGetOrdersList mocks base method.
func (m *MockStorageProvider) StorageGetOrdersList(ctx context.Context, login string) ([]models.OrdersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageGetOrdersList", ctx, login)
	ret0, _ := ret[0].([]models.OrdersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StorageGetOrdersList indicates an expected call of StorageGetOrdersList.
func (mr *MockStorageProviderMockRecorder) StorageGetOrdersList(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageGetOrdersList", reflect.TypeOf((*MockStorageProvider)(nil).StorageGetOrdersList), ctx, login)
}

// StorageGetUserBalance mocks base method.
func (m *MockStorageProvider) StorageGetUserBalance(ctx context.Context, login string) (models.LoginBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageGetUserBalance", ctx, login)
	ret0, _ := ret[0].(models.LoginBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StorageGetUserBalance indicates an expected call of StorageGetUserBalance.
func (mr *MockStorageProviderMockRecorder) StorageGetUserBalance(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageGetUserBalance", reflect.TypeOf((*MockStorageProvider)(nil).StorageGetUserBalance), ctx, login)
}

// StorageGetWithdrawalsList mocks base method.
func (m *MockStorageProvider) StorageGetWithdrawalsList(ctx context.Context, login string) ([]models.WithdrawalsList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageGetWithdrawalsList", ctx, login)
	ret0, _ := ret[0].([]models.WithdrawalsList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StorageGetWithdrawalsList indicates an expected call of StorageGetWithdrawalsList.
func (mr *MockStorageProviderMockRecorder) StorageGetWithdrawalsList(ctx, login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageGetWithdrawalsList", reflect.TypeOf((*MockStorageProvider)(nil).StorageGetWithdrawalsList), ctx, login)
}

// StorageNewOrderLoad mocks base method.
func (m *MockStorageProvider) StorageNewOrderLoad(ctx context.Context, login, orderNum string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageNewOrderLoad", ctx, login, orderNum)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorageNewOrderLoad indicates an expected call of StorageNewOrderLoad.
func (mr *MockStorageProviderMockRecorder) StorageNewOrderLoad(ctx, login, orderNum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageNewOrderLoad", reflect.TypeOf((*MockStorageProvider)(nil).StorageNewOrderLoad), ctx, login, orderNum)
}

// StorageNewOrderUpdate mocks base method.
func (m *MockStorageProvider) StorageNewOrderUpdate(ctx context.Context, login string, dc models.OrderSatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageNewOrderUpdate", ctx, login, dc)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorageNewOrderUpdate indicates an expected call of StorageNewOrderUpdate.
func (mr *MockStorageProviderMockRecorder) StorageNewOrderUpdate(ctx, login, dc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageNewOrderUpdate", reflect.TypeOf((*MockStorageProvider)(nil).StorageNewOrderUpdate), ctx, login, dc)
}

// StorageNewWithdrawal mocks base method.
func (m *MockStorageProvider) StorageNewWithdrawal(ctx context.Context, login string, dc models.NewWithdrawal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StorageNewWithdrawal", ctx, login, dc)
	ret0, _ := ret[0].(error)
	return ret0
}

// StorageNewWithdrawal indicates an expected call of StorageNewWithdrawal.
func (mr *MockStorageProviderMockRecorder) StorageNewWithdrawal(ctx, login, dc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StorageNewWithdrawal", reflect.TypeOf((*MockStorageProvider)(nil).StorageNewWithdrawal), ctx, login, dc)
}
